version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "docker"
    directory: "/httpserver"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "golang"
        versions: '> 1.22'
    commit-message:
      prefix: "chore"

  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "vscode/devcontainers/go"
        versions: '> 1.22'
    commit-message:
      prefix: "chore"
