name: high-availability

on:
  pull_request_target:
    types: [labeled]
  pull_request:
    branches:
      - main
      - dev
      - 1.0.0*
  push:
    branches:
      - 1.0.0*
      - main
      - dev
  workflow_dispatch:

permissions: read-all

jobs:
  build_test_replica:
    name: "Build and run replica test"
    runs-on: ubuntu-latest
    timeout-minutes: 25
    continue-on-error: true
    permissions:
      contents: read
    strategy:
      matrix:
        DAPR_VERSION: ["1.13.2"]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          egress-policy: audit

      - name: Check out code into the Go module directory
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Go 1.22
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: '1.22'

      - name: Bootstrap e2e
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          make e2e-bootstrap
          make generate-certs
      - name: Run e2e
        run: |
          make e2e-deploy-gatekeeper
          make e2e-helm-deploy-ratify-replica DAPR_VERSION=${{ matrix.DAPR_VERSION }}
          make test-high-availability
      - name: Save logs
        if: ${{ always() }}
        run: |
          kubectl logs -n gatekeeper-system -l control-plane=controller-manager --tail=-1 > logs-externaldata-controller-${{ matrix.DAPR_VERSION }}.json
          kubectl logs -n gatekeeper-system -l control-plane=audit-controller --tail=-1 > logs-externaldata-audit-${{ matrix.DAPR_VERSION }}.json
          kubectl logs -n gatekeeper-system -l app=ratify --tail=-1 > logs-ratify-preinstall-${{ matrix.DAPR_VERSION }}.json
          kubectl logs -n gatekeeper-system -l app.kubernetes.io/name=ratify --tail=-1 > logs-ratify-${{ matrix.DAPR_VERSION }}.json
      - name: Upload artifacts
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        if: ${{ always() }}
        with:
          name: e2e-logs-${{ matrix.DAPR_VERSION }}
          path: |
            logs-*.json
