name: quick-start

permissions:
  contents: read

on:
  pull_request_target:
    types: [labeled]
  pull_request:
    branches:
      - main
      - dev
      - 1.0.0*
  push:
    branches:
      - 1.0.0*
      - dev
      - main
  workflow_dispatch:

jobs:
  test-quick-start:
    name: "Run quick start test"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    strategy:
      matrix:
        KUBERNETES_VERSION: ["1.29.2"]
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: setup go environment
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: "1.21"
      - name: Run tidy
        run: go mod tidy
      - name: Bootstrap e2e
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          make e2e-bootstrap KUBERNETES_VERSION=${{ matrix.KUBERNETES_VERSION }}
          make generate-certs
      - name: Run e2e with config policy
        run: |
          make e2e-helmfile-install
          make e2e-helmfile-deploy-released-ratify
          make test-quick-start
      - name: Save logs
        if: ${{ always() }}
        run: |
          kubectl logs -n gatekeeper-system -l app=ratify --tail=-1 > logs-ratify-preinstall-${{ matrix.KUBERNETES_VERSION }}-config-policy.json
          kubectl logs -n gatekeeper-system -l app.kubernetes.io/name=ratify --tail=-1 > logs-ratify-${{ matrix.KUBERNETES_VERSION }}-config-policy.json
      - name: Upload artifacts
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        if: ${{ always() }}
        with:
          name: e2e-logs-${{ matrix.KUBERNETES_VERSION }}
          path: |
            logs-*.json
