name: scan_vulns
on:
  push:
    paths-ignore:
      - "docs/**"
      - "library/**"
      - "**.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "library/**"
      - "**.md"
  schedule:
    - cron: '30 8 * * 0'  # early morning (08:30 UTC) every Sunday
  workflow_dispatch:

permissions: read-all

jobs:
  govulncheck:
    name: "Run govulncheck"
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          egress-policy: audit

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: "1.22"
          check-latest: true
      - uses: golang/govulncheck-action@dd0578b371c987f96d1185abb54344b44352bd58 # v1.0.3

  scan_vulnerabilities:
    name: "[Trivy] Scan for vulnerabilities"
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          egress-policy: audit

      - name: Check out code into the Go module directory
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Download trivy
        run: |
          pushd $(mktemp -d)
          wget https://github.com/aquasecurity/trivy/releases/download/v${{ env.TRIVY_VERSION }}/trivy_${{ env.TRIVY_VERSION }}_Linux-64bit.tar.gz
          tar zxvf trivy_${{ env.TRIVY_VERSION }}_Linux-64bit.tar.gz
          echo "$(pwd)" >> $GITHUB_PATH
        env:
          TRIVY_VERSION: "0.46.0"

      - name: Run trivy on git repository
        run: |
          trivy fs --format table --ignore-unfixed --scanners vuln .

      - name: Build docker images
        run: |
          make e2e-build-local-ratify-image
          make e2e-build-crd-image
      - name: Run trivy on images for all severity
        run: |
          for img in "localbuild:test" "localbuildcrd:test"; do
              trivy image --ignore-unfixed --vuln-type="os,library" "${img}"
          done
      - name: Run trivy on images and exit on HIGH severity
        run: |
          for img in "localbuild:test" "localbuildcrd:test"; do
              trivy image --ignore-unfixed --exit-code 1 --severity HIGH --vuln-type="os,library" "${img}"
          done
