name: Sync GH Pages
on:
  push:
    branches:
    - main
    paths:
    - library/**

permissions: read-all

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
      - uses: everlytic/branch-merge@c4a244dc23143f824ae6c022a10732566cb8e973
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'gh-pages'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'